["Content Toggles"]
	#Disabling these will make the corresponding feature unobtainable/unusable
	#Should hammers be enabled? This tool can create new block variants and destroy some blocks faster. (default: true)
	enableHammers = true
	#Should wrenches be enabled? This tool can change the rotation of some blocks. (default: true)
	enableWrenches = true
	#Should asphalt be enabled? (default: true)
	enableAsphalt = true
	#Should vertical stairs be enabled? (default: true)
	enableVerticalStairs = true
	#Should blocks made out of resources (gold, diamond, etc) be enabled? (default: true)
	enableResourceBricks = true
	#Should shelf variants be enabled? (default: true)
	enableShelfVariants = true
	#Should decorative shelf blocks be enabled? (default: true)
	enableDecorativeShelves = true
	#Should crafting table variants be enabled? (default: true)
	enableCraftingTableVariants = true
	#Should ladder variants be enabled? (default: true)
	enableLadderVariants = true
	#Should Excessive Building's pottery sherds be enabled? (default: true)
	enableEBPotterySherds = true
	#Should new candles that produce particles when lit be enabled? (default: true)
	enableParticleCandles = true
	#Should terracotta pots that can be filled and hold flowers be enabled?? (default: true)
	enableTerracottaPots = true
	#Should small decoration blocks (jars, mugs, etc) be enabled? (default: true)
	enableDecoratives = true
	#Should ancient saplings be enabled (and to extension their content)? (default: true)
	enableAncientSaplings = true
	#Should gloom seeds be enabled (and to extension their content)? (default: true)
	enableGloomSeeds = true

["Balance Configuration"]
	#Configuration for features that may impact gameplay in a large way
	#Should the hammer have weapon like abilities? Increased knockback based on movement speed and increased damage. (default: true)
	enableHammerAsWeapon = true
	#Should Excessive Building add new trade offers to villagers? (default: true)
	enableEBVillagerTrades = true
	#Should soul magma bubble columns be toggled with redstone? (default: true)
	enableSoulMagmaColumnToggle = true
	#Should reaching lanterns grant nearby players the reaching effect? (default: true)
	enableReachingLanternFunctionality = true
	#What level of reaching should the reaching lantern grant? (default: 1)
	#Range: 0 ~ 255
	reachingLanternAmplifier = 1
	#How large should the reaching lantern's range be in blocks? (default: 8)
	#Range: 0 ~ 64
	reachingLanternRange = 8
	#How long should the reaching potion last in ticks? (default: 12000)
	#Range: 0 ~ 72000
	reachingDuration = 12000
	#How long should the long reaching potion last in ticks? (default: 24000)
	#Range: 0 ~ 72000
	longReachingDuration = 24000
	#What level of reaching should the reaching potion grant? (default: 2)
	#Range: 0 ~ 255
	reachingAmplifier = 2
	#What level of reaching should the strong reaching potion grant? (default: 4)
	#Range: 0 ~ 255
	strongReachingAmplifier = 4
	#How long should the shortening potion last in ticks? (default: 6000)
	#Range: 0 ~ 72000
	shorteningDuration = 6000
	#How long should the long shortening potion last in ticks? (default: 12000)
	#Range: 0 ~ 72000
	longShorteningDuration = 12000
	#What level of shortening should the shortening potion grant? (default: 1)
	#Range: 0 ~ 255
	shorteningAmplifier = 1
	#What level of shortening should the strong shortening potion grant? (default: 2)
	#Range: 0 ~ 255
	strongShorteningAmplifier = 2
	#How long should the ancient fruit's reaching last in ticks? (default: 600)
	#Range: 0 ~ 72000
	ancientFruitDuration = 600
	#What level of reaching should the ancient fruit grant? (default: 1)
	#Range: 0 ~ 255
	ancientFruitAmplifier = 1
