hideOverlays = "ALL"
rgbProgress = false
blockOverlay = false
miniRender = true
enableScissor = false
type = "TEXT_WITH_BACKGROUND"
reloadText = "Edit in config!"
resetResources = true
reInitScreen = true
removeOverlayAtEnd = true
earlyPackStatusSend = false
doubleLoad = "FORCE_LOAD"
animationSpeed = 1000.0
